### ISSUE TITLE
Guide for installing in Hassbian

### ISSUE THREAD

**Issue by snelweg** [marconfus/ha-nefit#13]
~~First install the dependencies:~~

~~`sudo pip3 install pyaes`~~
~~`sudo pip3 install sleekxmpp`~~

~~Then you can install the client:~~
~~`sudo pip3 install nefit-client`~~

~~Do not forget~~
~~`sudo pip3 install voluptuous`~~

Thanks to  @marconfus 

!!!!!!!!!!!!! https://community.home-assistant.io/t/nefit-easy-client/8148/

Important!!!!
 **sudo su - homeassistant**

So as the user that is running Homeassistant you should run the following:

```
source /srv/homeassistant/bin/activate
pip3 install nefit-client
```

Follow the instructions in the readme.md file

(custom_components)

> it should be in /home/homeassistant/.homeassistant/custom_components/climate/nefit.py

`https://community.home-assistant.io/t/solved-custom-components-directory-with-hassbian/40185`

**Comment by chiel2603** [comment]
Hello,

I'm new to Home Assistant.
Currently running version 0.84.6 in Hassbian (Raspberry Pi 3B).

I did all the steps:
- Login as homeassistant;
- source /srv/homeassistant/bin/activate;
- pip3 install pyaes (needed for pip3 install nefit-client);
- pip3 install sleekxmpp (needed for pip3 install nefit-client);
- pip3 install nefit-client;
- pip3 install voluptuous (allready installed);
- git clone https://github.com/marconfus/ha-nefit;
- Copy nefit.py to /home/homeassistant/.homeassistant/custom_components/climate;
- Edit nefit.py config with netfit easy information;
- Restart Home Assistant;

But I see nothing popping up in Home Assistant.
Do I need to add something in my configuration.yaml?

I would love to add my nefit easy to Home Assistant.

**Comment by chiel2603** [comment]
I allso add:
climate:
  platform: nefit
  name: Heating
  serial: 'XXXXXXXXX'
  accesskey: 'xxxxxxxxx'
  password: 'xxxxxxxxx'
  holiday_temp: 7
  holiday_duration: 31
To the configuration.yaml, with the nefit information ofcourse.
error message in Home Assistent:
Invalid config for [climate.nefit]: required key not provided @ data['MYPASSWORD']. Got None required key not provided @ data['MYSERIAL']. Got None required key not provided @ data['Nefit Easy Thermostaat']. Got None required key not provided @ data['MYACCESKEY']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/climate.nefit/

**Comment by chiel2603** [comment]
I have put back the information in nefit.py to:
CONF_NAME = "name"
CONF_SERIAL = "serial"
CONF_ACCESSKEY = "accesskey"
CONF_PASSWORD = "password"
CONF_HOLIDAY_TEMP = "holiday_temp"
CONF_HOLIDAY_DURATION = "holiday_duration"
First I had my Nefit information in it.

Not I have "Klimaat" in HASS with "heating auto".
I don't see a way to change temps or reading current temps.

**Comment by snelweg** [comment]
> I have put back the information in nefit.py to:
> CONF_NAME = "name"
> First I had my Nefit information in it.

Why would you want to do that?
 
> Not I have "Klimaat" in HASS with "heating auto".
> I don't see a way to change temps or reading current temps.

So it is working now?

ps: please use the <code> tags so your posting is more readable.

**Comment by chiel2603** [comment]
> In the command line I fount an error. :
nefit-client --serial XXXXXXXXX --access-key XXXXXXXXXXXXXXXX, --password XXXXXXXXXX
Traceback (most recent call last): File "/srv/homeassistant/bin/nefit-client", line 11, in <module> sys.exit(main()) File "/srv/homeassistant/lib/python3.5/site-packages/nefit/cli.py", line 92, in main cli.run() File "/srv/homeassistant/lib/python3.5/site-packages/nefit/cli.py", line 60, in run print(client.get_status()) File "/srv/homeassistant/lib/python3.5/site-packages/nefit/__init__.py", line 287, in get_status for k, v in data.items(): AttributeError: 'str' object has no attribute 'items'>

I have no idea what this error means, nor how to solve it.

**Comment by TimSoethout** [comment]
Maybe the `,` at the end of your acces-key fails the authentication? And
this error is the result of this later in the code.

**Comment by chiel2603** [comment]
The "," was my fault in my last post, sorry. I double checked with "nefit-client --serial XXXXXXXXX --access-key XXXXXXXXXXXXXXXX --password XXXXXXXXXX --status" got the same result.

**Comment by chiel2603** [comment]
It's working! It was a password problem. Thank you all for the help! :)

**Comment by marconfus** [comment]
New development continues in this repository: https://github.com/marconfus/ha-nefit-ng
