### ISSUE TITLE
Unpack error in log

### ISSUE THREAD

**Issue by trizz** [marconfus/ha-nefit#14]
Hi all. I've finally got this custom component working on my HASS installation, I can see the current/target temp and set the temp. However, this error keeps appearing in my logs:

```
[custom_components.climate.nefit] Nefit api returned invalid data: too many values to unpack (expected 2)
```

Is there any way how I can debug this?

**Comment by marconfus** [comment]
New development continues in this repository: https://github.com/marconfus/ha-nefit-ng
