### ISSUE TITLE
Guide for installing on hassio

### ISSUE THREAD

**Issue by jilleb** [marconfus/ha-nefit#6]
Installing on hassio seems to go slighty different than usual. Is it possible to write a guide on how to get it running on a Hassio distro?

**Comment by marconfus** [comment]
Sorry, I am not using Hassio, so I can‘t say anything about it. But I do plan to get it integrated into mainline Homeassistant. I hope to find some time to do this soon.

**Comment by tomlevels** [comment]
I am also interested in running this in Hassio, any update on this?

**Comment by mories76** [comment]
I've got it working under HassIO.

Enable SSH access as described in [https://developers.home-assistant.io/docs/en/hassio_debugging.html](url)

Then SSH to hassio.local
ssh root@hassio.local -p 22222

#run shell in homeassistant docker containter
docker exec -it homeassistant /bin/bash 

# define user base directory
export PYTHONUSERBASE=/config/deps
#install pyaes
pip3 install --user --no-cache-dir --prefix= --no-dependencies pyaes
#install nefit-client 0.2.2
# 0.2.5 didn't work for me, got certificate expired messages
pip3 install --user --no-cache-dir --prefix= --no-dependencies nefit-client==0.2.2

I hope this works for other people as well.

**Comment by KuiBar** [comment]
I got the following error and hope anybody could help me. I am running HomeAssistant in a VenV.:


(homeassistant) homeassistant@Hassio:/home/kuibar$ sudo pip3 install --user --no-cache-dir --prefix= --no-dependencies nefit-client
Collecting nefit-client
  Downloading https://files.pythonhosted.org/packages/c8/74/57b04fc5ec52cec473ebc13cd63852f26fd98ec3a9181befbbc59438dc67/nefit-client-0.2.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6eoutzrr/nefit-client/setup.py", line 5, in <module>
        from nefit import version
      File "/tmp/pip-build-6eoutzrr/nefit-client/nefit/__init__.py", line 8, in <module>
        from sleekxmpp import ClientXMPP
    ModuleNotFoundError: No module named 'sleekxmpp'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6eoutzrr/nefit-client/

**Comment by mories76** [comment]
I've added a custom dependency needed after upgrading to version 0.81.

If you're already running  0.80 and the Nefit custom component.  Do the following
Then SSH to hassio.local
ssh root@hassio.local -p 22222
```
# at the hassio> prompt
login

# now at the bash-4.4# prompt
docker exec -it homeassistant /bin/bash
export PYTHONUSERBASE=/config/deps
pip3 install --user --no-cache-dir --prefix= --no-dependencies pyasn1==0.3.7
```

**Comment by Toxik1983** [comment]
> ```
> pip3 install --user --no-cache-dir --prefix= --no-dependencies pyasn1==0.3.7
> ```
Confirmed working, thanks @mories76 !
Here's a useful hint for people who installed HA on Docker directly instead of using Hass.io, you need to use:
```
export PYTHONUSERBASE=/usr/local
```
Instead of:
```
export PYTHONUSERBASE=/config/deps
```
Follow the rest of the instructions exactly as posted above, minus the login. You can confirm it's working by running nefit-client directly:
```
nefit-client --serial 12345678 --access-key abcdefghijklmnop --password mysecret --status
```

**Comment by frenck** [comment]
Wowzers.

Just got referred to this from a community topic. This stuff listed above is just the worst ever and I would definitely not recommend anyone to follow the above instructions.

**Comment by frenck** [comment]
Well, this component is just not created correctly. If it was, Home Assistant would just install the dependencies it needed on first use.

First of all, the version of the `nefit-client` isn't pinned:

https://github.com/marconfus/ha-nefit/blob/master/nefit.py#L9

Secondly, requirements should not be imported globally, but only inside functions. This is necessary because requirements are installed on the fly, using its current construction, this component will fail before HA even has the chance the `netfit-client`.

https://github.com/marconfus/ha-nefit/blob/master/nefit.py#L25

So this is not a Hass.io issue, the component is just simply not following the design of Home Assistant.

**Comment by mories76** [comment]
@frenck Thanx for the feedback, I understand that all off the above is not best practice at all.
But it was intended as a workaround.
I've looked at the issues of pinning and importing, could you please be so kind to look at #18 and see if this is what you meant. Please be gentle ;-)
It works this way without the ugly custom_deps hack, but that's not a guarantee that things are as are supposed to be. Thx!

**Comment by mories76** [comment]
Anyone else willing to try the version of the script from #18 ?
I cleared my deps folder, or you could even rename it. And it works as expected.

**Comment by snelweg** [comment]
KI would love to test this.
But HA ate my fourth sd card and I lost all confidence in HA. I am not the only one with a lot of damage to the SD card. I have Raspberry PI's and Orange zero pi running Armbian for months without problem.

Hope HA will fix the SD cards problems soon.

**Comment by marconfus** [comment]
New development continues in this repository: https://github.com/marconfus/ha-nefit-ng
